# Set up locally by running
#
# $ pre-commit install
#
# See https://pre-commit.com/
default_language_version:
  python: python3

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: "20.8b1"
  hooks:
    - id: black
- repo: https://github.com/mgedmin/check-manifest
  rev: "0.46"
  hooks:
    - id: check-manifest
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.812"
  hooks:
    - id: mypy
      files: "metricq/"
